services:
  app:
    build: .
    container_name: conveter
    depends_on:
      - db
    environment: 
      DATABASE_URL = "postgres://mitia:conv@db:5432/conveter?sslmode=disable"
    ports:
      - "8080:8080"
  db:
    image: postgres:18.1
    container_name: conveter-db
    environment:
      PS_USER: mitia
      PS_PASSWORD: conv
      PS_DB: conveter
    ports:
       - "5432-5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
  