CREATE TABLE IF NOT EXISTS Currencies (
    id SERIAL PRIMARY KEY,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(10) NOT NULL
);

INSERT INTO Currencies (code, name, symbol) VALUES
('USD', 'United States Dollar', '$'),
('EUR', 'Euro', '€'),
('JPY', 'Japanese Yen', '¥'),
('GBP', 'British Pound Sterling', '£'),
('AUD', 'Australian Dollar', 'A$'),
('CAD', 'Canadian Dollar', 'C$'),
('CHF', 'Swiss Franc', 'CHF'),
('CNY', 'Chinese Yuan', '¥'),
('SEK', 'Swedish Krona', 'kr'),
('NZD', 'New Zealand Dollar', 'NZ$'),
('MXN', 'Mexican Peso', '$'),
('SGD', 'Singapore Dollar', 'S$'),
('HKD', 'Hong Kong Dollar', 'HK$'),
('NOK', 'Norwegian Krone', 'kr'),
('KRW', 'South Korean Won', '₩'),
('TRY', 'Turkish Lira', '₺'),
('RUB', 'Russian Ruble', '₽'),
('INR', 'Indian Rupee', '₹'),
('BRL', 'Brazilian Real', 'R$'),
('ZAR', 'South African Rand', 'R'),
('DKK', 'Danish Krone', 'kr'),
('PLN', 'Polish Zloty', 'zł'),
('TWD', 'New Taiwan Dollar', 'NT$'),
('THB', 'Thai Baht', '฿'),
('MYR', 'Malaysian Ringgit', 'RM'),
('IDR', 'Indonesian Rupiah', 'Rp'),
('CZK', 'Czech Koruna', 'Kč'),
('HUF', 'Hungarian Forint', 'Ft'),
('ILS', 'Israeli New Shekel', '₪'),
('CLP', 'Chilean Peso', '$'),
('PHP', 'Philippine Peso', '₱'),
('AED', 'United Arab Emirates Dirham', 'د.إ'),
('COP', 'Colombian Peso', '$'),
('SAR', 'Saudi Riyal', 'ر.س'),
('RON', 'Romanian Leu', 'lei'),
('NGN', 'Nigerian Naira', '₦'),
('PKR', 'Pakistani Rupee', '₨'),
('VND', 'Vietnamese Dong', '₫'),
('EGP', 'Egyptian Pound', '£'),
('BDT', 'Bangladeshi Taka', '৳'),
('KZT', 'Kazakhstani Tenge', '₸'),
('QAR', 'Qatari Riyal', 'ر.ق'),
('KWD', 'Kuwaiti Dinar', 'د.ك'),
('DZD', 'Algerian Dinar', 'دج'),
('MAD', 'Moroccan Dirham', 'د.م.'),
('UAH', 'Ukrainian Hryvnia', '₴'),
('GHS', 'Ghanaian Cedi', '₵'),
('OMR', 'Omani Rial', 'ر.ع.'),
('JOD', 'Jordanian Dinar', 'د.ا'),
('LBP', 'Lebanese Pound', 'ل.ل'),
('TND', 'Tunisian Dinar', 'د.ت'),
('AZN', 'Azerbaijani Manat', '₼'),
('BYN', 'Belarusian Ruble', 'Br'),
('LKR', 'Sri Lankan Rupee', 'රු'),
('KES', 'Kenyan Shilling', 'KSh'),
('GEL', 'Georgian Lari', '₾'),
('IRR', 'Iranian Rial', '﷼'),
('XOF', 'West African CFA Franc', 'CFA'),
('XAF', 'Central African CFA Franc', 'FCFA'),
('BHD', 'Bahraini Dinar', 'ب.د'),
('MUR', 'Mauritian Rupee', '₨'),
('CRC', 'Costa Rican Colón', '₡'),
('PEN', 'Peruvian Sol', 'S/'),
('UYU', 'Uruguayan Peso', '$U'),
('DOP', 'Dominican Peso', 'RD$'),
('JMD', 'Jamaican Dollar', 'J$'),
('XPF', 'CFP Franc', '₣'),
('MNT', 'Mongolian Tögrög', '₮'),
('AMD', 'Armenian Dram', '֏'),
('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM'),
('MKD', 'Macedonian Denar', 'ден'),
('ALL', 'Albanian Lek', 'L'),
('GMD', 'Gambian Dalasi', 'D'),
('SZL', 'Swazi Lilangeni', 'E'),
('NAD', 'Namibian Dollar', 'N$'),
('BBD', 'Barbadian Dollar', 'Bds$'),
('BTN', 'Bhutanese Ngultrum', 'Nu.'),
('FJD', 'Fijian Dollar', 'FJ$'),
('GYD', 'Guyanese Dollar', 'G$'),
('HTG', 'Haitian Gourde', 'G'),
('JEP', 'Jersey Pound', '£'),
('KMF', 'Comorian Franc', 'CF'),
('MGA', 'Malagasy Ariary', 'Ar'),
('MVR', 'Maldivian Rufiyaa', 'Rf'),
('SBD', 'Solomon Islands Dollar', 'SI$'),
('SLL', 'Sierra Leonean Leone', 'Le'),
('SRD', 'Surinamese Dollar', '$'),
('TJS', 'Tajikistani Somoni', 'SM'),
('TOP', 'Tongan Paanga', 'T$'),
('WST', 'Samoan Tala', 'WS$'),
('XCD', 'East Caribbean Dollar', 'EC$'),
('YER', 'Yemeni Rial', '﷼'),
('ZMW', 'Zambian Kwacha', 'ZK'),
('BND', 'Brunei Dollar', 'B$'),
('CUP', 'Cuban Peso', '₱'),
('ERN', 'Eritrean Nakfa', 'Nfk'),
('GNF', 'Guinean Franc', 'FG'),
('KGS', 'Kyrgyzstani Som', 'сом'),
('LRD', 'Liberian Dollar', 'L$'),
('MOP', 'Macanese Pataca', 'P'),
('MRO', 'Mauritanian Ouguiya', 'UM'),
('SYP', 'Syrian Pound', '£S'),
('TMT', 'Turkmenistani Manat', 'm'),
('VUV', 'Vanuatu Vatu', 'VT'),
('ZWL', 'Zimbabwean Dollar', 'Z$'),
('CUC', 'Cuban Convertible Peso', '$'),
('XAU', 'Gold Ounce', 'Au'),
('XAG', 'Silver Ounce', 'Ag'),
('XPT', 'Platinum Ounce', 'Pt'),
('XPD', 'Palladium Ounce', 'Pd'),
('SDG', 'Sudanese Pound', '£Sd'),
('SSP', 'South Sudanese Pound', '£SS'),
('BWP', 'Botswana Pula', 'P'),
('CDF', 'Congolese Franc', 'FC'),
('SZL', 'Eswatini Lilangeni', 'E'),
('TND', 'Tunisian Dinar', 'د.ت'),
('UGX', 'Ugandan Shilling', 'USh'), 
('AFN', 'Afghan Afghani', '؋'),
('BZD', 'Belize Dollar', 'BZ$'),
('BIF', 'Burundian Franc', 'FBu'),
('CVE', 'Cape Verdean Escudo', 'Esc'),
('DJF', 'Djiboutian Franc', 'Fdj'),
('ETB', 'Ethiopian Birr', 'Br'),
('FKP', 'Falkland Islands Pound', '£'),
('GIP', 'Gibraltar Pound', '£'),
('HNL', 'Honduran Lempira', 'L'),
('KPW', 'North Korean Won', '₩'),
('LSL', 'Lesotho Loti', 'M'),
('MZN', 'Mozambican Metical', 'MT'),
('NPR', 'Nepalese Rupee', '₨'),
('SHP', 'Saint Helena Pound', '£'),
('TPE', 'Timorese Escudo', 'Esc'),
('VEB', 'Venezuelan Bolívar', 'Bs'),
('XSU', 'Sucre', 'Sucre'),
('ZWL', 'Zimbabwean Dollar', 'Z$'),
('COU', 'Colombian Real Value Unit', 'UVR'),
('STN', 'São Tomé and Príncipe Dobra', 'Db'),
('VES', 'Venezuelan Sovereign Bolívar', 'Bs.S'),
('BYR', 'Belarusian Ruble (pre-2016)', 'Br'),
('RSD', 'Serbian Dinar', 'дин'),
('TWD', 'Taiwan Dollar', 'NT$');